### ISSUE TITLE
Bug: BERKSHIRE can't be selected as first stock

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-investments#110]
whenever I try to select BERKSHIRE... as my first stock, it just doesn't show the config box. When I first add another stock and add BERKSHIRE later, everything works as normal. I've only seen this with this one company, haven't tested widely though

**Comment by ArtInLines** [comment]
The bug only happens with BERKSHIRE. The reason behind the bug is, that we assume to have the dates for the earliest and latest times that we are able to get data from the stock. I had tried to fix that, but that caused some other weird bugs lol. For now, I'm ignoring to solve this more long-term, as we might not even cache that data after all.

In any case, the simple fix for now is to simply remove BERKSHIRE from the cached list of stocks.
