### ISSUE TITLE
Reverb causes Cracking

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#144]
With the following Mapping I got some very bad sound quality (especially from the middle of the playback onward). I'm not sure what causes this though

- Dates from 2000 to 2023
- Audio Length = 2:30
- Vodafone: Price -> Retro Synth: Pitch
- Exxon: Price      -> Retro Synth: Relvolume
- Meta: Price       -> Retro Synth: Delay Echo
- Alibaba: Price   -> Retro Synth: Feedback Echo
- Apple: Price     -> Retro Synth: Delay Reverb

(Note: This were tested after my fix of #143, bc it crashed otherwise)
(Note: I also tested this a couple of times, and the sound always had the same bad quality)

**Comment by nichtLehdev** [comment]
We've run out of queries for today. Any chance you exported the file?

**Comment by ArtInLines** [comment]
I sadly did not 😢 But I can sign up to the API with a couple more email adresses and get us more API keys. The website is here if you want to help get some more API keys: https://leeway.tech/auth/login

**Comment by nichtLehdev** [comment]
I'll do what I can

**Comment by Rex2002** [comment]
seems to be an issue related to the reverb, I will look into that, if t
he reverb is removed the sound is ok I think
[Börsen-Sonifizierung.wav.zip](https://github.com/Rex2002/sound-investments/files/11691576/Borsen-Sonifizierung.wav.zip) (zipping was necessary, because github does not support .wav)

**Comment by ArtInLines** [comment]
@Rex2002 I agree, the file you sent has a good quality 👍

**Comment by Rex2002** [comment]
Note: not necessarily worth, just a collection of things that did not work.
so the problem lies with the changing delay values. 
Since reverb is basically just adding what one heard a half a second ago to what one is hearing now, the cracking jumps into existence when we suddenly change that "half a second" to "three quarter of a second" because the data obviously is not continuous then. 
I thought about a completely different reverberation-approach using comb- and allpass-filters, but since for this approach the delay is more or less directly translated to filter-frequency of the comb-filter is believe that this would also create cracking noises.
Another approach was to create the reverb one at a time, but trying to let it fade between reverb-delay-time-changes. 
This approach unfortunately ended up sounding like a Sitar. 
I am not quite sure if thats because of an error in the idea or faulty implementation.
The third approach, being the most costly in terms of calculation, also adds reverberation one at a time, but each delay-value is applied on the whole array once, only the feedback values are altered, such that the feedback is close to zero everywhere, where that delay-value is not supposed to be. 
This yielded good results for short delay-arrays, but ended up crappy when using bigger delay-arrays, because even the close-to-zero-feedback led to very high values at certain spots, which then lead to the whole array being scaled down to close to zero (except those spots), hence one could not hear anything.
When setting the default feedback to 0 the values did not add up to close to infinity, but the cracking reappeared, because of the zeroed-feedback.
So the todo for tomorrow is to add some sort of curve / decay / whatever to the feedback.

**Comment by Rex2002** [comment]
Edit: smoothing the feedback change does not seem to work, either the volume-decrease is too high again (slow smoothing) or the cracking returns (steeper smoothing).

Also noticed that this issue also effects echo-delay-times.

**Comment by Rex2002** [comment]
Approach 5 (I think): only treating the given delay-values as target values and changing the actual delay-value on steps of 1, each time a full delay-cycle is completed. 
Result: sounds like an angry bee...
Approach 6: Altering the code of a free-reverb tool that is based on four simultaneous combFilters followed by two sequential allpass-filters (based on the standard Schroeder/Moorer reverb) to use changing delay values.
Result: cracking

**Comment by ArtInLines** [comment]
@Rex2002 I have pretty much no idea about this topic, but if it would be of use to you, I could offer to be your (rubber duck)[https://en.wikipedia.org/wiki/Rubber_duck_debugging] - basically listening to you explain the problem and offering another set of eyes for solving the problem

**Comment by Rex2002** [comment]
Approach 7: fading between changing delay-values by adding some sort of envelope to the feedback, such that the feedback is always zero when the delay value changes. 
This works moderately good, if the number of delay-values is less than 1/3 of the soundlength in seconds. 
Only problem is that somehow randomly cracks can be heard. I could not yet find a way to distinguish a cracking-free-delay-array from one that produces one or more cracks.
