### ISSUE TITLE
impact boom sounds weird on my device

### ISSUE THREAD

**Issue by Rex2002** [Rex2002/sound-investments#197]

**Comment by MalteRichert** [comment]
Happens on my device too, don't know what causes it though. My current theory is that the other ev-instrs crack just as much, but we don't hear it because their high frequencies are closer to the cracking. I think this because this issue has stayed when I switched out the BOOM sample entirely from a sample that had nothing to do with the current except that both are bass-heavy

**Comment by Rex2002** [comment]
seems to be a general issue with my speakers / global sampling rate
