### ISSUE TITLE
Steigung doesn't seem to work

### ISSUE THREAD

**Issue by nichtLehdev** [Rex2002/sound-investments#204]
Tested on global-cleanup

Stocks tested:
Apple Inc (AAPL)
Vodafone

Mapping:
Retro Synth.Pitch -> Price
From 17/05/2018 to today

Testresult:
With Apple. The Pitch is a constant tone which doesn't change at all.
With Vodafone. The Slope seems to work for the first 2 seconds but afterwards falls to the same constant tone as with Apple

Not completely sure where the error lives here..

**Comment by nichtLehdev** [comment]
getRelChange Method in Analyser seems to bring the expected results. May be a harmoniser problem while converting?

**Comment by MalteRichert** [comment]
@nichtLehdev I'm not sure I understand the problem. Didn't you map the prices to pitch? Mapping the prices obviously has nothing to do with analysis of "Steigung", right? Or did you mean you mapped "Steigung" to pitch?

**Comment by nichtLehdev** [comment]
Yeah I mapped the Slope..

**Comment by nichtLehdev** [comment]
Sry for confusion xD

**Comment by ArtInLines** [comment]
@MalteRichert I think I found the issue. The slope doesn't have a high standard deviation, but since it's mapped to pitch, we are reducing its range. Thus, in the end, barely any changes in the slope are audible.

Proposed solution: Take a lower standard-deviation cutoff point for slopes and alternatively only do the standard-deviation calculation if the price is mapped to the pitch

**Comment by Rex2002** [comment]
`double[] pitch = calcLineData(instrMap.getPitch(), priceMap, instrMap.getPitch().getData() == LineData.PRICE);`

would this suffice? @ArtInLines

**Comment by ArtInLines** [comment]
@Rex2002 yes probably. However, it seems that the slope data never takes on very big values (even without reducing the range). I think we could solve that by applying a low-pass filter over the data before calculating the slope. I will try that out and see if we get better results with it.

**Comment by ArtInLines** [comment]
It might actually also be that the normalization algorithm fails with negative numbers. I will test that now

**Comment by ArtInLines** [comment]
The Blur also doesn't seem to help. When `isPitch` is false, the values seem to mostly all fall into a range of 0.18 to 0.3. With `isPitch` true, they fall into the range of 0.45 to 0.55 instead. Neither is what we actually want. My first naive attempt at using the blur didn't help much either. I have two ideas of how to fix this rn.

1. Using a better or bigger blur / using the blur slightly differently.
2. I fear that our linear nomalization might not be a good idea for slope. Currently, we basically just set the normalized value to how close the value was to the maximum in a linear fashion. If we instead had a function where small steps close at the middle were translated into bigger normalized steps, we might solve this.
 
However, since it's already late, I might just leave it as it is, if I can't find a good working solution

**Comment by Rex2002** [comment]
if you are looking to blur arrays of double values, the Effect.IIR might be of help to try out different blurring-strengths,

but I think leaving it as it is should also be just fine

**Comment by ArtInLines** [comment]
Thx for the idea, I'll try it out 👍

**Comment by ArtInLines** [comment]
Focused on more important stuff instead
