### ISSUE TITLE
Reverb doesn't appear as "good" as before

### ISSUE THREAD

**Issue by nichtLehdev** [Rex2002/sound-investments#213]
The Reverb Parameter makes close to no difference (if at all) to our Audio output. 
As we had a pretty obvious reverb effect some time ago, I think that we might have an issue resolving in those (not/barely audible) effects

**Comment by Rex2002** [comment]
I think the problem might be that our max_reverb_delay is 2205 (which is barely hearable already) and that that value is seldomly reached as well (because that obviously only occurs when the rawDelay is close to 1 -> since we do a lot of averaging there, that probably does not happen particularly often)
proposed "fix" would be to increase the max_reverb_delay to maybe 4410 or something like that
