### ISSUE TITLE
UI: double-click start button

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-investments#67]
Sometimes, when the sonification takes a second to load, I can click the start button a second time which will result in two sonifications playing at the same time, the second one slightly delayed. The Button should be deactivated after being pressed the first time.

**Comment by ArtInLines** [comment]
I prevented sonifying the mapping several times in 01c00b2 - I decided not to disable the button though because we actually wanted to show some kind of loading bar. That way it would be clear to the user that clicking the button or changing parameters in the mapping has no effect anymore. If you want, we can still disable the button anyways though

**Comment by ArtInLines** [comment]
As of 3af7962 the loading animation was added too.
