### ISSUE TITLE
No sonifiables are shown in MainScene after coming from musicScene

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#71]
After switching from music scene back to the main scene, no data is shown anymore. It seems like the initialize() method isn't being called, but I don't know why that would be the case

**Comment by MalteRichert** [comment]
I experienced this too and found that in most cases (not all though) I could just switch categories to "Aktien" and back to "Alle Kategorien" and everything would be there again. Maybe that helps.

**Comment by ArtInLines** [comment]
d1391aa seems to have solved the issue for me, even though I have no idea how lol. Does the issue persist for you still @MalteRichert ?

**Comment by MalteRichert** [comment]
Nope, hasn't disappeared for me. It's still there sometimes, it don't see a regularity though.
Things more generally get weird when you stop once and then try to sonny again. I've just had the same problem twice that I pressed start on the second configuration and playback started but the UI kept on loading. This message came along with it in the console:
`Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.setScene(javafx.scene.Scene)" because "stage" is null
	at app.ui.MainSceneController.switchToMusicScene(MainSceneController.java:254)
	at app.ui.MainSceneController.lambda$initialize$0(MainSceneController.java:139)
`

**Comment by ArtInLines** [comment]
Oh interesting, thx for copy-pasting the exception. I think I know where the bug lies now, even though I'm not sure yet how to fix it. I will look into it again some other time

**Comment by MalteRichert** [comment]
Encountered the issue again, this time with a different exception:
`Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at util.ArrayFunctions.clampedArrAccess(ArrayFunctions.java:53)
	at app.ui.MusicSceneController$2.toString(MusicSceneController.java:172)
	at app.ui.MusicSceneController$2.toString(MusicSceneController.java:170)`

**Comment by ArtInLines** [comment]
Was fixed in 965735a
