### ISSUE TITLE
Make UI resizable

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#88]
Very, very low priority. But if I want to distract myself from the stress of the exams, I might want to make the entire UI resizable. Currently we also set all positions of all UI elements manually, which would then be done much more effectively, cleanly and automatically via formulas

**Comment by MalteRichert** [comment]
@ArtInLines I'd upgrade the priority at least a little. On my device, I can never see the entire window because it is too wide for my screen. I'm not sure on what kind of a screen Kruse works but it sure wouldn't be nice if he ends up with the same problem.
I'm aware though that this might be quite a drastic rewrite so...

**Comment by ArtInLines** [comment]
I have spent more time than I am willing to admit on this. However, I seem incapable of getting it done in the provided timeframe, so I will close this issue and ignore the pain behind my wasted work

**Comment by MalteRichert** [comment]
So sorry, I'm sure you learned some things in the process 👀 
The UI is fine as it is though, this isn't a big deal
